src/Entity/Painting.php
<?php

namespace App\Entity;

use App\Repository\PaintingRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PaintingRepository::class)
 */
class Painting
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $width;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $height;

    /**
     * @ORM\Column(type="boolean")
     */
    private $onSale;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $price;

    /**
     * @ORM\Column(type="datetime")
     */
    private $completionDate;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $file;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="paintings")
     */
    private $user;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, inversedBy="paintings")
     */
    private $category;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private $portfolio;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="painting")
     */
    private $comments;


    public function __construct()
    {
        $this->category = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getWidth(): ?string
    {
        return $this->width;
    }

    public function setWidth(string $width): self
    {
        $this->width = $width;

        return $this;
    }

    public function getHeight(): ?string
    {
        return $this->height;
    }

    public function setHeight(string $height): self
    {
        $this->height = $height;

        return $this;
    }

    public function getOnSale(): ?bool
    {
        return $this->onSale;
    }

    public function setOnSale(bool $onSale): self
    {
        $this->onSale = $onSale;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCompletionDate(): ?\DateTimeInterface
    {
        return $this->completionDate;
    }

    public function setCompletionDate(\DateTimeInterface $completionDate): self
    {
        $this->completionDate = $completionDate;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(string $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->category;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->category->contains($category)) {
            $this->category[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        $this->category->removeElement($category);

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getPortfolio(): ?bool
    {
        return $this->portfolio;
    }

    public function setPortfolio(bool $portfolio): self
    {
        $this->portfolio = $portfolio;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPainting($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPainting() === $this) {
                $comment->setPainting(null);
            }
        }

        return $this;
    }
}

src/Controller/PaintingController.php
<?php

namespace App\Controller;

use App\Entity\Painting;
use App\Repository\PaintingRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PaintingController extends AbstractController
{
    private PaintingRepository $paintingRepository;
    private PaginatorInterface $paginator;
    private EntityManagerInterface $em;

    public function __construct
    (PaintingRepository $paintingRepository,
     EntityManagerInterface $em,
     PaginatorInterface $paginator
    )
    {
        $this->paintingRepository = $paintingRepository;
        $this->paginator = $paginator;
        $this->em = $em;
    }


    /**
     * @Route("/realisations", name="realisations")
     */
    public function index(Request $request): Response
    {
        $dql   = "SELECT p FROM App:Painting p";
        $query = $this->em->createQuery($dql);
        $paintingList = $this->paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            6

        );
        return $this->render('painting/realisations.html.twig', [
            'paintingList' => $paintingList,
        ]);
    }
    /**
     * @Route("/realisations/{slug}", name="realisations_detail")
     */
    public function detail(Painting $painting): Response
    {
        return $this->render('painting/detail.html.twig', [
            'painting' => $painting,
        ]);
    }
}

templates/painting/detail.html.twig
{% extends 'base/base.html.twig' %}

{% block body %}
    <div class="row mt-5">
        <div class="col-4">
            <h1>{{ painting.name }}</h1>
            <div>
                {% for c in painting.categories.toArray %}
                    <span class="bg-dark text-white rounded-3 p-1">{{ c.name }}</span>
                {% endfor %}
            </div>

            <div>{{ painting.description }}</div>
            <div class="d-flex justify-content-between">
                <span class="">Largeur:</span>
                <span class="">{{ painting.width }}</span>
            </div>
            <div class="d-flex justify-content-between">
                <span class="">Hauteur:</span>
                <span class="">{{ painting.height }}</span>
            </div>
            <div class="d-flex justify-content-between">
                <span class="">Réalisé le:</span>
                <span class="">{{ painting.completionDate|date('d/m/Y') }}</span>
            </div>
            {% if painting.onSale %}
                <div class="d-flex justify-content-between">
                    <span class="">Disponible à la vente:</span>
                    <span class="">{{ painting.price }}€</span>
                </div>
            {% endif %}
        </div>
        <div class="col-8">
            <img class="img-fluid" src="{{ painting.file }}" alt="{{ painting.name }}">
        </div>
    </div>
{% endblock %}


templates/painting/realisations.html.twig
{% extends 'base/base.html.twig' %}
{% block body %}
    <div class="mx-3 my-5">Toutes les Réalisations</div>
    <div class="d-flex flex-wrap justify-content-center">
        {% if paintingList|length > 0 %}
            {% for p in paintingList %}
                <div class="my-2 mx-2">
                    <div class="card" style="width: 18rem;">
                        <img src="{{ p.file }}" class="card-img-top" alt="{{ p.name }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ p.name }}</h5>
                            <p class="card-text">{{ p.description|u.truncate(200,'...',false) }}</p>
                            <a href="{{ path('realisations_detail', {'slug': p.slug}) }}" class="btn btn-primary">voir la
                                peinture</a>
                        </div>
                        <div class="card-footer">
                            <p class="card-text text-muted small">
                                {{ p.createdAt|date('d/m/Y') }}
                            </p>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div>Aucun contenu pour le moment</div>
        {% endif %}
    </div>
    <div class="d-flex justify-content-center">
        {{ knp_pagination_render(paintingList,'base/pagination.html.twig') }}
    </div>
{% endblock body %}